require("src.plugins-setup")
require("src.core.options")
require("src.core.keymaps")
require("src.core.colorscheme")
require("src.plugins.comment")
require("src.plugins.presence")
require("src.plugins.nvim-tree")
require("src.plugins.lualine")
require("src.plugins.nvim-cmp")
require("src.plugins.lsp.mason")
require("src.plugins.lsp.lspsaga")
require("src.plugins.lsp.lspconfig")
-- require("src.plugins.telescope")
